import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`min-h-screen ${inter.className} bg-cyan-100  justify-center`}>
        <Navbar />
        <div className="container mx-auto flex-column justify-center items-center bg-cyan-100 text-white pb-10px my-10 ">
          {children}
        </div>
      </body>
    </html >
  );
}
